language: php

php:
  - '7.2'
  - '7.3'
  - master

matrix:
  allow_failures:
    - php: master
  fast_finish: true

before_install:
  - composer self-update
  - composer clear-cache

install:
  - composer install --no-interaction

script:
  - phpunit --coverage-clover=coverage.xml
  - vendor/bin/phpcs src --standard=PSR2
  - vendor/bin/phpcbf src
  - vendor/bin/phpa src
  - vendor/bin/phpmnd src

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml
