name: Run tests

on: [push]

jobs:
  unit-tests:
    strategy:
      matrix:
        php: [7.2, 7.3, 7.4]
        dependency-version: [prefer-lowest, prefer-stable]
        os: [windows-latest, ubuntu-latest, macos-latest]
    name: PHP${{ matrix.php }} with ${{ matrix.dependency-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, libxml
          tools: prestissimo
          coverage: xdebug
      - name: Composer install
        run: |
          composer install --dev --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest
      - name: Composer test
        run: |
          composer test-${{ matrix.os }}
