name: Run tests

on: [push]

jobs:
  unit-tests:
    strategy:
      fail-fast: false
      matrix:
        php: [8.1, 8.2, 8.3]
        dependency-version: [prefer-lowest, prefer-stable]
        os: [ubuntu-latest]
        test: [phpunit, phan, phpmd, phpcs, phpcbf, churn, phpstan, psalm]
    name: ${{ matrix.test }} on PHP${{ matrix.php }} with ${{ matrix.dependency-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, libxml, mbstring
          coverage: xdebug
      - name: Composer self-update
        run: |
          composer self-update
      - name: Composer update
        run: |
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest
      - name: Composer test-${{ matrix.test }}-${{ matrix.os }}
        run: |
          composer test-${{ matrix.test }}-${{ matrix.os }}

  coverage:
    name: PHPUnit test coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, libxml
          tools: phpunit
          coverage: xdebug
      - name: Composer self-update
        run: |
          composer self-update
      - name: Composer update
        run: |
          composer update --prefer-dist --no-interaction --no-suggest
      - name: Get coverage
        run: |
          phpunit --coverage-clover=coverage.xml
      - name: Send coverage report
        run: |
          wget https://scrutinizer-ci.com/ocular.phar
          php ocular.phar code-coverage:upload --format=php-clover coverage.xml
